#000 | play story in the call implementation added
Sunbird-AIAssistant/ivrs-bot pull request #1
Opened 2023-12-13 06:54 UTC by kumarks1122

2023-12-13 09:15 UTC, maheshkumargangula requested changes

2023-12-13 09:15 UTC, maheshkumargangula commented on python/voice-streaming/server.py
> +    audio = AudioSegment.from_wav(file_path)
Looks like it works with only wav file. We should support mp3 file and using a public url. Please make the required changes for it.

2023-12-13 09:17 UTC, kumarks1122 commented on python/voice-streaming/server.py
> +    audio = AudioSegment.from_wav(file_path)
sure

2024-01-04 11:17 UTC, maheshkumargangula approved these changes

2024-01-04 11:18 UTC, merged